import { v } from "convex/values";

export const paymentAttemptValidators = {
  billing_date: v.number(),
  charge_type: v.string(),
  created_at: v.number(),
  failed_at: v.optional(v.number()),
  failed_reason: v.optional(v.object({
    code: v.string(),
    decline_code: v.optional(v.string()),
  })),
  gateway_external_id: v.optional(v.string()),
  id: v.string(),
  instance_id: v.string(),
  paid_at: v.optional(v.number()),
  payment_id: v.string(),
  statement_id: v.string(),
  status: v.string(),
  updated_at: v.number(),
  payer: v.object({
    email: v.string(),
    first_name: v.string(),
    last_name: v.string(),
    user_id: v.string(),
    id: v.string(),
    image_url: v.optional(v.string()),
    organization_id: v.optional(v.string()),
    organization_name: v.optional(v.string()),
  }),
  payment_source: v.object({
    card_type: v.string(),
    last4: v.string(),
    gateway: v.optional(v.string()),
    gateway_external_account_id: v.optional(v.string()),
    gateway_external_id: v.optional(v.string()),
    id: v.string(),
    payment_method: v.optional(v.string()),
    status: v.optional(v.string()),
  }),
  subscription_items: v.array(v.object({
    amount: v.object({
      amount: v.number(),
      amount_formatted: v.string(),
      currency: v.string(),
      currency_symbol: v.string(),
    }),
    id: v.string(),
    plan: v.object({
      id: v.string(),
      name: v.string(),
      slug: v.string(),
      amount: v.number(),
      currency: v.string(),
      period: v.string(),
      interval: v.number(),
      is_default: v.boolean(),
      is_recurring: v.boolean(),
      description: v.optional(v.string()),
    }),
    status: v.string(),
    period_start: v.number(),
    period_end: v.number(),
    plan_id: v.string(),
    canceled_at: v.optional(v.number()),
  })),
  totals: v.object({
    grand_total: v.object({
      amount: v.number(),
      amount_formatted: v.string(),
      currency: v.string(),
      currency_symbol: v.string(),
    }),
    subtotal: v.object({
      amount: v.number(),
      amount_formatted: v.string(),
      currency: v.string(),
      currency_symbol: v.string(),
    }),
    tax_total: v.object({
      amount: v.number(),
      amount_formatted: v.string(),
      currency: v.string(),
      currency_symbol: v.string(),
    }),
  }),
};

export const paymentAttemptDataValidator = v.object(paymentAttemptValidators);

export const paymentAttemptSchemaValidator = v.object({
  ...paymentAttemptValidators,
  userId: v.optional(v.id("users")),
});

export function transformWebhookData(data: any) {
  return {
    billing_date: data.billing_date,
    charge_type: data.charge_type,
    created_at: data.created_at,
    failed_at: data.failed_at,
    failed_reason: data.failed_reason,
    gateway_external_id: data.gateway_external_id,
    id: data.id,
    instance_id: data.instance_id,
    paid_at: data.paid_at,
    payment_id: data.payment_id,
    statement_id: data.statement_id,
    status: data.status,
    updated_at: data.updated_at,
    payer: {
      email: data.payer.email,
      first_name: data.payer.first_name,
      last_name: data.payer.last_name,
      user_id: data.payer.user_id,
      id: data.payer.id,
      image_url: data.payer.image_url,
      organization_id: data.payer.organization_id,
      organization_name: data.payer.organization_name,
    },
    payment_source: {
      card_type: data.payment_source.card_type,
      last4: data.payment_source.last4,
      gateway: data.payment_source.gateway,
      gateway_external_account_id: data.payment_source.gateway_external_account_id,
      gateway_external_id: data.payment_source.gateway_external_id,
      id: data.payment_source.id,
      payment_method: data.payment_source.payment_method,
      status: data.payment_source.status,
    },
    subscription_items: data.subscription_items.map((item: any) => ({
      amount: {
        amount: item.amount.amount,
        amount_formatted: item.amount.amount_formatted,
        currency: item.amount.currency,
        currency_symbol: item.amount.currency_symbol,
      },
      id: item.id,
      plan: {
        id: item.plan.id,
        name: item.plan.name,
        slug: item.plan.slug,
        amount: item.plan.amount,
        currency: item.plan.currency,
        period: item.plan.period,
        interval: item.plan.interval,
        is_default: item.plan.is_default,
        is_recurring: item.plan.is_recurring,
        description: item.plan.description,
      },
      status: item.status,
      period_start: item.period_start,
      period_end: item.period_end,
      plan_id: item.plan_id,
      canceled_at: item.canceled_at,
    })),
    totals: {
      grand_total: {
        amount: data.totals.grand_total.amount,
        amount_formatted: data.totals.grand_total.amount_formatted,
        currency: data.totals.grand_total.currency,
        currency_symbol: data.totals.grand_total.currency_symbol,
      },
      subtotal: {
        amount: data.totals.subtotal.amount,
        amount_formatted: data.totals.subtotal.amount_formatted,
        currency: data.totals.subtotal.currency,
        currency_symbol: data.totals.subtotal.currency_symbol,
      },
      tax_total: {
        amount: data.totals.tax_total.amount,
        amount_formatted: data.totals.tax_total.amount_formatted,
        currency: data.totals.tax_total.currency,
        currency_symbol: data.totals.tax_total.currency_symbol,
      },
    },
  };
}